web/routes/index.py
import os
import uuid

from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app,
    make_response
    )
from werkzeug.datastructures import FileStorage

import secret
from models.message import Messages
from models.reply import Reply
from models.topic import Topic
from models.user import User
from routes import current_user, cache
from routes import current_user, csrf_required, login_required

import json
import time

from utils import log

main = Blueprint('index', __name__)


@main.route("/")
def index():
    time.sleep(0.5)
    return render_template('login.html')


@main.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        form = request.form.to_dict()
        u = User.register(form)
        log('注册成功!')
        return redirect(url_for('.index'))

    return render_template('register.html')


@main.route("/login", methods=['GET', 'POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        log('账号或密码错误，登录失败!')
        return redirect(url_for('.index'))
    else:
        # flask session 改为 redis 存储的session
        session_id = str(uuid.uuid4())
        key = 'session_id_{}'.format(session_id)
        cache.set(key, u.id)

        redirect_to_index = redirect(url_for('topic.index'))
        response = current_app.make_response(redirect_to_index)
        response.set_cookie('session_id', value=session_id, max_age=3600)

        return response


@main.route("/logout", methods=['GET'])
@login_required
def logout():
    redirect_to_index = redirect(url_for('.index'))
    response = current_app.make_response(redirect_to_index)
    response.delete_cookie('session_id')

    return response


def created_topic(user_id):
    ts = Topic.all(user_id=user_id)
    return ts


def replied_topic(user_id):
    k = 'replied_topic_{}'.format(user_id)
    if cache.exists(k):
        v = cache.get(k)
        ts = json.loads(v)
        return ts
    else:
        rs = Reply.all(user_id=user_id)
        ts = []
        for r in rs:
            t = Topic.one(id=r.topic_id)
            ts.append(t)

        v = json.dumps([t.json() for t in ts])
        cache.set(k, v)

        return ts


@main.route('/profile')
@login_required
def profile():
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
@login_required
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
@login_required
def avatar_add():
    file: FileStorage = request.files['avatar']
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg', 'png']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/images/{}'.format(filename))

        return redirect(url_for('.profile'))


@main.route('/images/<filename>')
@login_required
def image(filename):
    return send_from_directory('images', filename)


@main.route('/setting', methods=['GET', 'POST'])
@login_required
def setting():
    u = current_user()
    if request.method == 'POST':
        username = request.form['username']
        signature = request.form['signature']
        u.update(id=u.id, username=username, signature=signature)
        log('修改用户名和个性签名成功')

    return render_template('setting.html', user=u)


@main.route('/setting/update_password', methods=['GET', 'POST'])
def setting_update_password():
    u = current_user()
    if request.method == 'POST':
        old_password = request.form['old_password']
        new_password = request.form['new_password']

        if u.salted_password(old_password) == u.password:
            u.password = u.salted_password(new_password)
            u.update(id=u.id, password=u.password)
            log('修改密码成功')

    return render_template('setting.html', user=u)


@main.route('/reset', methods=['GET', 'POST'])
def reset_password():
    return render_template('reset.html')


@main.route('/reset/send', methods=['GET', 'POST'])
def reset():
    """
    找回密码
    """
    username = request.form['username']
    u = User.one(username=username)

    token = str(uuid.uuid4())
    cache.set(token, u.id, ex=3600)

    content = '{}/reset/view?token={}'.format(secret.dns, token)
    Messages.send(
        title='找回密码',
        content=content,
        sender_id=u.id,
        receiver_id=u.id
    )

    return redirect(url_for('.index'))


@main.route('/reset/view', methods=['GET', 'POST'])
def reset_view():
    token = request.args['token']
    if token is not None:
        return render_template('reset_view.html', token=token)
    else:
        return redirect(url_for('.index'))


@main.route('/reset/update/<token>', methods=['GET', 'POST'])
def reset_update(token):
    if token is not None:
        user_id = cache.get(token)
        log('user_id:', user_id)
        u = User.one(id=int(user_id))
        new_password = request.form['password']

        u.update(id=user_id, password=u.salted_password(new_password))
        log('重置密码成功')

    return redirect(url_for('.index'))

web/routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
@login_required
def index():
    board_id = int(request.args.get('board_id', -1))
    u = current_user()
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<int:id>')
@login_required
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@login_required
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    t = Topic.one(id=id)

    if t.user_id == u.id:
        Topic.delete(id)

    return redirect(url_for('.index'))


@main.route("/new")
@login_required
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@login_required
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

web/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>

    <link href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/index.css" media="all">
    <link rel="stylesheet" href="/static/css/new.css" media="all">
    <link rel="stylesheet" href="/static/css/sign_in.css">

    <script async="" src="/static/js/analytics.js"></script>
    <script src="/static/js/index.min.f7c13f64.min.js"></script>
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand navbar-left" href="#">Snow Bean</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('topic.index') }}">首页</a></li>

                    <li><a href="{{ url_for('index.setting') }}">设置</a></li>
                    {% if current_user() %}
                        <li>
                            <a href="{{ url_for('index.logout') }}">退出</a>
                        </li>
                    {% else %}
                        <li>
                            <a class="" href="{{ url_for('index.index') }}">登录</a>
                        </li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

{% endblock %}

{% block content %}
{% endblock %}

{% block tail %}
    <footer class="footer">
      <div class="container">
          <div class="col-md-4"></div>
          <div class="col-md-4"><p class="text-muted"></p></div>
          <div class="col-md-4"></div>
      </div>
    </footer>
{% endblock %}
</body>
</html>

web/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>

</body>
</html>

web/templates/login.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
     <div class="container">
      <form class="form-signin" method="post" action="{{ url_for('.login') }}">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label class="control-label">Username</label>
        <input type="text" id="inputUsername" class="form-control" name="username" value="gua" required autofocus>
        <label class="control-label">Password</label>
        <input type="password" id="inputPassword" class="form-control" name="password" value="123"
               placeholder="Password" required>
        <button class="btn btn-primary" type="submit">Login</button>
           <a href="{{ url_for('index.register') }}">没有账号？注册一个</a>
                            <a id="forgot_password" href="{{ url_for('index.reset_password') }}">忘记密码了?</a>
      </form>

    </div> <!-- /container -->
{% endblock %}

web/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <div class="container">
    <div class="col-md-3"></div>

    <div class="col-md-6">
<h1>用户资料页面</h1>
<div>
    {{ user.id }}
</div>
<div>
    {{ user.username }}
</div>

<div>
    <div>创建的</div>
    {% for t in created %}
        <a href="{{ url_for('topic.detail', id=t.id) }}">{{ t.title }}</a>
    {% endfor %}
</div>
<div>
    <div>参与的</div>
    {% for t in replied %}
        <a href="{{ url_for('topic.detail', id=t.id) }}">{{ t.title }}</a>
    {% endfor %}
</div>

<form method="post"
      action="{{ url_for('.avatar_add')}}"
      enctype="multipart/form-data"
>
    <input type="file" name="avatar">
    <button type="submit">上传头像</button>
</form>

<img src="{{ user.image }} ">
    </div>
    <div class="col-md-3"></div>
</div>
{% endblock %}

web/templates/register.html
{% extends 'base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
     <div class="container">
      <form class="form-signin" method="post" action="{{ url_for('.register') }}">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label class="control-label">Username</label>
        <input type="text" id="inputUsername" class="form-control" name="username" value="gua" required autofocus>
        <label class="control-label">Password</label>
        <input type="password" id="inputPassword" class="form-control" name="password" value="123"
               placeholder="Password" required>
          <label class="control-label">邮箱</label>
          <input type="text" class="input-xlarge" name="email"><br>

        <button class="btn btn-primary" type="submit">Register</button>
      </form>

    </div> <!-- /container -->
{% endblock %}

web/templates/reset.html
{% extends 'base.html' %}

{% block title %}
    Find Password
{% endblock %}

{% block content %}
    <div class="container">
      <form class="form-signin" method="post" action="{{ url_for('.reset') }}">
        <h2 class="form-signin-heading">Find Password</h2>
        <label class="control-label">Username</label>
        <input type="text" id="inputUsername" class="form-control"
               name="username" value="gua" required autofocus>
        <button class="btn btn-primary" type="submit">找回密码</button>
      </form>
    </div> <!-- /container -->
{% endblock %}

web/templates/reset_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>重置密码</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
<form class="form-horizontal" method="post" action="{{ url_for('.reset_update', token=token) }}">
        <div class="control-group">
            <label class="control-label">新密码</label>
            <div class="controls">
                <input type="password" class="input-xlarge" name="password">
            </div>
        </div>

        <div class="form-actions">
            <input type="submit" class="span-primary" value="重置密码">
        </div>
    </form>
</body>
</html>

web/templates/setting.html
{% extends 'base.html' %}

{% block title %}
        gua
{% endblock %}


{% block content %}
<!-- navbar -->
</div>
<div id="main">
    <div id="sidebar">

        <div class="panel">

            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="#">
                            <img src="{{ user.image }}" title="user_img">
                        </a>
                        <span class="user_name">
                            <a class="dark"
                               href="#">{{ user.username }}
                            </a>
                        </span>

                        <div class="board clearfix">

                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div id="content">
        <div class="panel">
            <div class="header">
                <ul class="breadcrumb">
                    <li><a href="#">主页</a><span class="divider">/</span></li>
                    <li class="active">设置</li>
                </ul>
            </div>
            <div class="inner">
                <form id="setting_form" class="form-horizontal" action="{{ url_for('.setting') }}" method="post">
                    <div class="control-group">
                        <label class="control-label" for="name">用户名</label>

                        <div class="controls">
                            <input class="input-xlarge readonly" id="name" name="username" size="30" type="text"
                                   value="">
                        </div>
                    </div>

                    <div class="control-group">
                        <label class="control-label" for="signature">个性签名</label>

                        <div class="controls">
                            <textarea class="input-xlarge" id="signature" name="signature" size="30"></textarea>
                        </div>
                    </div>
                    <input type="hidden" id="action" name="action" value="change_setting">
                    <input type="hidden" name="_csrf" value="i8rs7HYw-_SiUkG6GnrUZfPjpp6CPMA_Y50U">

                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" value="保存设置">
                    </div>
                </form>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">更改密码</span>
            </div>
            <div class="inner">
                <form id="change_pass_form" class="form-horizontal" action="{{ url_for('.setting_update_password') }}"
                      method="post">
                    <div class="control-group">
                        <label class="control-label" for="old_pass">当前密码</label>

                        <div class="controls">
                            <input class="input-xlarge" type="password" id="old_pass" name="old_password" size="30">
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="new_pass">新密码</label>

                        <div class="controls">
                            <input class="input-xlarge" type="password" id="new_pass" name="new_password" size="30">
                        </div>
                    </div>
                    <input type="hidden" id="action" name="action" value="change_password">
                    <input type="hidden" name="_csrf" value="i8rs7HYw-_SiUkG6GnrUZfPjpp6CPMA_Y50U">

                    <div class="form-actions">
                        <input type="submit" class="span-primary submit_btn" value="更改密码">
                    </div>
                </form>
            </div>
        </div>

        <div class="panel">
            <div class="header">
                <span class="col_fade">上传头像</span>
            </div>
            <div class="inner">
                <div>

                </div>
                <div>
                    <form method="post"
                          action="{{ url_for('.avatar_add') }}"
                          enctype="multipart/form-data">
                        <input type="file" name="avatar">
                        <button type="submit" class="span-primary submit_btn">上传头像</button>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}