web/models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

web/routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    Request)

from models.message import Messages
from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


def users_from_content(content):
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, reply_link, reply_content):
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        title = '你被 {} AT 了'.format(sender.username)
        Messages.send(
            title=title,
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )


@main.route("/add", methods=["POST"])
@login_required
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, request.referrer, content)

    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

web/routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
@login_required
def index():
    board_id = int(request.args.get('board_id', -1))
    u = current_user()
    if board_id == -1:
        ms = Topic.all()
    else:
        ms = Topic.all(board_id=board_id)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", ms=ms, token=token, bs=bs, bid=board_id, user=u)


@main.route('/<int:id>')
@login_required
def detail(id):
    m = Topic.get(id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m)


@main.route("/delete")
@login_required
@csrf_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    t = Topic.one(id=id)

    if t.user_id == u.id:
        Topic.delete(id)

    return redirect(url_for('.index'))


@main.route("/new")
@login_required
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@login_required
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))

web/templates/topic/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ topic.title }}
{% endblock%}

{% block content %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | time }}
            </span>
                    <span>
                {% set u = topic.user() %}
                作者 {{ u.username }}
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content}}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span>{{ r.created_time | time }}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content }}</div>

                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>

{% endblock %}

web/templates/topic/index.html
{% extends "base.html" %}
{% block title %}论坛主页{% endblock%}
{% block content %}

<div id="main">
    <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar" href="#">
                            <img src="{{ user.image }}" title="user_img">
                        </a>
                        <span class="user_name">
                            <a class="dark"
                               href="#">{{ user.username }}
                            </a>
                        </span>

                        <div class="board clearfix">

                        </div>
                        <div class="space clearfix"></div>
                        <span class="signature">
                            {{ user.signature }}
                        </span>
                    </div>
                </div>
            </div>

            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>回复:{{ t.replies() | count }} / 阅读:{{ t.views }}</span>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>

{% endblock %}

web/templates/topic/new.html
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>

{% block content %}
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
                        <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea><br>
                            <span class="tab-selector">选择版块：</span>
                            <select name="board_id" id="board" required>
                                {% for b in bs %}
                                    {% if bid == b.id %}
                                        <option value="{{ b.id }}" selected>{{ b.title }}</option>
                                    {% else %}
                                        <option value="{{ b.id }}">{{ b.title }}</option>
                                    {% endif %}
                                {% endfor %}
                            </select>
                            <div class='markdown_editor in_editor'>
                                <div class='markdown_in_editor'>
                                    <textarea class='editor' name='content' rows='20'
                                              placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                    <div class='editor_buttons'>
                                        <input type="submit" class='span-primary submit_btn' data-loading-text="提交中"
                                               value="提交">
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        (function () {
            var editor = new Editor();
            editor.render($('.editor')[0]);
        })();
    </script>
{% endblock %}

web/templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link href="//cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/style.css">

</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>